apiVersion: v1
kind: Service
metadata:  
  name: backend-service
spec:
  selector:
    name: backend-pod
    app: bootapp  
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
