apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-frontend

spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels: 
      name: frontend-pod
      app: bootapp
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: bootapp
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
          - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: URL_BACKEND
              value: {{ .Values.frontend.env.url }}